### ISSUE TITLE
SAR command doesn't work

### ISSUE THREAD

**Issue by kbreit** [pahud/lambda-layer-awscli#13]
I am trying to import the `awscli` layer into my function and am experiencing errors. Initially I tried to simply import via `arn` (not in the instructions, I know) and the string is too long. Then I ran the command you provide and received:

```
aws --region us-east-2 serverlessrepo create-cloud-formation-template --application-id arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-awscli

An error occurred (AccessDeniedException) when calling the CreateCloudFormationTemplate operation: User: arn:aws:iam::804798220069:user/api-user is not authorized to perform: serverlessrepo:CreateCloudFormationTemplate on resource: arn:aws:serverlessrepo:us-east-1:903779448426:applications/lambda-layer-awscli
``` 

If I need some IAM permissions to do this, the documentation should show this.

**Comment by pahud** [comment]
@kbreit thanks for the feedback. Looking into this now.

**Comment by pahud** [comment]
I just updated the `README` with inline policy sample. FYR. Let me know if you still encounter any issue and your PR will be highly appreciated as well.
